steps:
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']

  - name: 'gcr.io/cloud-builders/yarn'
    args: ['test']

  - name: 'gcr.io/cloud-builders/yarn'
    args: ['build']

  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy']